config/routes.rb
 PostitTemplate::Application.routes.draw do
  
  root to: 'posts#index'
 
  get 'register', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  


  resources :posts, except: :destroy do
    member do
      post :vote
    end
  	resources :comments, only: :create do
     member do
      post :vote
    end
    end
  end
  
  resources :categories
  resources :users
  
end

app/models/concerns/category.rb
class Category < ActiveRecord::Base;
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: :true

  before_save :create_slug


  def create_slug
  	self.slug = self.name.parameterize
  end

  def to_param
  	slug
  end

end

app/models/concerns/comment.rb
class Comment < ActiveRecord::Base;
   include Voteable

   belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
   belongs_to :post
   validates :body, presence: true
   
   has_many :votes, as: :voteable


  def total_votes
  	self.up_votes - self.down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end
  
end

app/models/concerns/post.rb
class Post < ActiveRecord::Base
  
  include Voteable

  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :comments

  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true
  validates :description, presence: true
  validates :url, presence: true


  before_save :create_slug

  
  def create_slug
    self.slug = self.title.parameterize
  end

  def to_param
    slug
  end

end

app/models/concerns/post_category.rb
class PostCategory < ActiveRecord::Base;
  belongs_to :post
  belongs_to :category
end

app/models/concerns/user.rb
class User < ActiveRecord::Base;
  has_many :posts
  has_many :comments

  has_secure_password validations: false
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 3}

  has_many :votes

  before_save :create_slug

  def create_slug
  	self.slug = self.username.parameterize
  end


  def to_param
  	slug
  end
 
  def admin?
    self.role == 'admin'
  end

  def moderator?
    self.role == 'moderator'
  end

end

app/models/concerns/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :voteable, polymorphic: true
	belongs_to :creator, class_name: 'User', foreign_key: 'user_id'

	validates_uniqueness_of :creator, :scope => [:voteable_type, :voteable_id]




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :require_user #makes these methods available to all views and controllers

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
  	if !logged_in?
  	flash[:error] = "You need to be logged in to do that"
  	redirect_to root_path
  	end
  end

  def require_admin
    if !logged_in? || !current_user.admin?
    flash[:error] = "You cannot do that"
    redirect_to root_path
    end
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

before_action :require_user, only: [:new, :create]
before_action :set_category, only: [:show, :edit, :update]
before_action :require_admin, only: [:new, :create]

 def index
 	@categories = Category.all
 end

 def show
 end

 def new
 	@category = Category.new
 end

 def create
 	@category = Category.new(params.require(:category).permit(:name))
 	 if @category.save
       flash[:notice] = "Category has been created"
       redirect_to root_path      
      else
        render :new
    end
 end

 def edit
 end

 def update
 end


private

  def set_category
  	@category = Category.find_by_slug(params[:id])
  end




end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :require_user
before_action :set_post

  def create
  	@comment = Comment.new(params.require(:comment).permit(:body))
    @comment.post = @post
    @comment.creator = current_user
  	
    if @comment.save
      flash[:notice] = "Your comment was saved"
      redirect_to post_path(@post)
  	else
      flash[:error] = "You've got to say something in your comment!"
  	  redirect_to :back
  	end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
         flash[:notice] = "Your vote was counted"
       else
          flash[:error] = "You can only vote once per comment"
        end
         redirect_to :back
       end
       format.js
       end 
  end


private

  def set_post
    @post = Post.find_by(slug: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]


  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
  end

  def show
    @comment = Comment.new

    respond_to do |format|
      format.html
      
    end

  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user 
      if @post.save
        flash[:notice] = "Successfully saved"
        redirect_to posts_path      
      else
        render :new
      end
  end

  def edit
  end

  def update

    if @post.update(post_params)
      flash[:notice] = "The post was updated"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid? 
          flash[:notice] = "Your vote was counted"
        else
          flash[:error] = "you can only vote once per post"
        end
          redirect_to :back
        end

      format.js
      
  end
end





private

  def post_params
    params.require(:post).permit(:title, :url, :slug, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by_slug(params[:id])
  end






end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
  	user = User.where(username: params[:username]).first
  	if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Successfully logged in"
      redirect_to root_path
  	else
      flash[:error] = "Incorrect username or password"
      redirect_to login_path
  	end
  end

  def destroy
  	session[:user_id] = nil
  	flash[:notice] = "You are now logged out"
  	redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :set_user, only: [:show, :edit, :update]

  def new
  	@user = User.new
  end

  def create
  	@user = User.create(user_params)
  	if @user.save
      session[:user_id] = @user.id
  		flash[:notice] = "Thank you for registering"
  		redirect_to posts_path
  	else
  		flash[:error] = "There was a problem, please try again"
  		render :new
  	end

  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User profile was updated"
      redirect_to user_path(@user)
    else
      render :edit
    end

  end


  def show
  end


  private

  def user_params
    params.require(:user).permit(:username, :password, :id, :slug, :time_zone)
  end

  def set_user
    @user = User.find_by_slug(params[:id])
  end




end

app/helpers/application_helper.rb
module ApplicationHelper

  def fix_url(str)
    str.start_with?("http://") ? str : "http://#{str}"
  end

  def nice_time(ts)
  	if logged_in? and !current_user.time_zone.blank?
  		ts = ts.in_time_zone(current_user.time_zone)
  	end

  	ts.strftime("on %e %b, %Y at %I:%M%P %Z")
  end

end

app/views/categories/index.html.erb
<% posts_link = link_to 'All Posts', posts_path %>

<%= render 'shared/content_title', title: "#{posts_link} &raquo; All Categories".html_safe %>

<% @categories.each do |category| %>
<div class='well'>
<%= category.name %>
</div>

<%end%>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'Create a new category' %>

<%= render 'shared/errors', obj: @category %>

<div class='well'>
<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %><br>
  <%= f.submit (@category.new_record? ? 'Create Category' : 'Update Category'),  class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% posts_link = link_to 'All Posts', posts_path %>

<%= render 'shared/content_title', title: "#{posts_link} &raquo; #{@category.name.capitalize}".html_safe %>

<% @category.posts.each do |post| %>
     <%= render 'posts/posts', post: post%>
<% end %>

app/views/comments/_comments.html.erb
<% @user.comments.each do |comment| %>
<div class="row">
  <div class='span8 well'>
    <em>"<%= comment.body  %>" -</em> <%=link_to comment.post.title, post_path(comment.post)%></p>
    <p class="quiet">By <%= link_to comment.creator.username, user_path(comment.creator) %> at <%= nice_time(comment.created_at) %></p>
  </div>
</div>
<% end %>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
$('#comment_<%=@comment.id %>_votes').html('<%=@comment.total_votes%> votes')
alert("Your vote was counted with ajax");
<% else %>
alert("You can only vote once per comment");
<% end %>
       

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>

<div class='btn-group nav_item'>
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %> 
    Categories <span class='caret'></span>
  <% end %>
  
  <ul class='dropdown-menu'>
  	<% Category.all.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
    <% end %>

  <% if logged_in? and current_user.admin? %>
    <li class='divider'></li>
    <li>
  	  <%= link_to(new_category_path) do %>
  	    <i class='icon-plus'></i>
  	    New Category
      <%end%>
    </li>
  <% end %>

  </ul>
   new_category_path, class: 'btn btn-success btn-small' %>
</div>

<div class='nav_item'>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
</div>

<div class="nav_item">
  <div class="btn-group">
  <% if !logged_in? %>
    <%= link_to 'Login', login_path, class: 'btn btn-default btn-small' %>
    <%= link_to 'Signup', register_path, class: 'btn btn-default btn-small'%>
   <% end %>
 </div>
</div>


<div class='btn-group nav_item'>
  <% if logged_in? %>
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
  <%= "#{current_user.username}" %><span class='caret'></span>
  <% end %>
  <ul class='dropdown-menu'>
  <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
  <li><%= link_to "View Profile", user_path(current_user) %></li>
  <li><%= link_to "Logout", logout_path %></li>
  <li>
  </ul>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
  <%= render 'shared/errors', obj: @post %>

<div class='well'>
<%= form_for @post do |f|%>
	<%=f.label :title %>
	<%=f.text_field :title, autofocus: true %>
	<%=f.label :url %>
	<%=f.text_area :url %>
	<%=f.label :description %>
	<%=f.text_area :description %>

	<%= f.label "Categories" %>
	<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
	<% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
	<% end %>

   

	<br>
	<%= f.submit (@post.new_record? ? 'Create Post' : 'Update Post'),  class: 'btn btn-primary' %>
<% end %>
</div>

app/views/posts/_posts.html.erb
<div class="row">

  <div class="span0 well text-center">

    <% if logged_in? %>
    <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
    <i class="icon-arrow-up"></i>
    <% end %>
    <% end %>

<br>

    <span id="post_<%=post.id%>_votes"><%= post.total_votes %> votes</span>

<br>

    <% if logged_in? %>
    <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
    <i class="icon-arrow-down"></i>
    <% end %>
    <% end %>


    <% if !logged_in? %>
    <p><%= link_to "Login to vote", new_user_path %></p>
    <% end %>
</div>


    <div class='span8 well'>
   	  <% post.categories.each do |category| %>
        <span class='badge'><%= link_to category.name, category_path(category) %></span>
      <%end%>
    <h4><%=link_to post.title.capitalize, post_path(post)%></h4>
    <p><%=post.description%></p>
    <p><span class='quiet'>posted by: </span><%= link_to "#{post.creator.username}", user_path(post.creator)%></p>
    <p><small><%= link_to "#{post.comments.size} comments", post_path(post)%></small></p>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this post' %>

<%= render 'form' %>

app/views/posts/index.html.erb
<% posts_link = link_to 'All Posts', posts_path %>

<%= render 'shared/content_title', title: posts_link %>

<div>
 
<% @posts.each do |post| %>
  <%= render 'posts', post: post %>
<% end %>
</div>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a new post' %>

<h4>Create a new post</h4>

<%= render 'form'%>

app/views/posts/show.html.erb
<p class='pull-right'>
	[<%= link_to 'edit this post', edit_post_path(@post)%>]
</p>


<p>
<% @post.categories.each do |category| %>
      <span class='badge'><%= category.name %></span>
<%end%><%= link_to "+", edit_post_path(@post) %>
</p>
<p class="lead"><%= link_to @post.title.capitalize, fix_url(@post.url) %></p>
<hr>
<p><%=@post.description%></p>
<hr>

<div class='well'>
	<%= form_for [@post, @comment] do |f| %>
	  <%= render 'shared/errors', obj: @comment %>
	  <%=f.label :body, 'Leave a comment:'%>
	  <%=f.text_area :body %>
	  <br>
	  <%= f.submit 'Create comment',  class: 'btn btn-primary' %>
    <% end %>
</div>


<h5>Comments:</h5>

<% @post.comments.each do |comment| %>
<div class="row">

  	<div class="span0 well text-center">
      <% if logged_in? %>
        <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
          <i class="icon-arrow-up"></i>
        <% end %>
      <% end %>

    <br>

      <span id="comment_<%=comment.id%>_votes"><%= comment.total_votes %> votes</span>

    <br>

      <% if logged_in? %>
        <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
          <i class="icon-arrow-down"></i>
        <% end %>
      <% end %>
      
      <% if !logged_in? %>
       <p><%= link_to "Login to vote", new_user_path %><p>
      <% end %>

    </div>


  <div class='span8 well'>
    <p><em>"<%= comment.body %>"</em></p>
    <p>
      <span class="quiet">by <%= link_to comment.creator.username, user_path(comment.creator) %> at <%= nice_time(comment.created_at) %></span>
    </p>
  </div>
  </div>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
$('#post_<%= @post.id %>_votes').html('<%= @post.total_votes %> votes')
alert("Your vote was counted with ajax");
<% else %>
alert("You can only vote once per post");
<% end %>

app/views/shared/_content_title.html.erb
<p class='lead'>
	<%= title %>
	<hr/>
</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class='row'>
     <div class='alert alert-error span8' >
      <h5> Please fix the following errors: </h5>
      <ul> 
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
     </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class='well'>
<%= form_for @user do |f|%>
	<%=f.label :username %>
	<%=f.text_field :username, autofocus: true %>
	<%=f.label :password %>
	<%=f.password_field :password %>
	<%=f.label :time_zone %>
	<%=f.time_zone_select :time_zone %>
	
	<br>
	
	<%= f.submit (logged_in? ? 'Submit' : 'Sign Up'),  class: 'btn btn-primary' %>
<% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: "Edit User: #{@user.username.capitalize}" %>

<%= render 'form' %>

app/views/users/new.html.erb
<% if logged_in? %>
  <%= render 'shared/content_title', title: "Please #{link_to "logout", logout_path} before signing up as a new user".html_safe %>
<% else %>
<% end %>

<% if !logged_in? %>
<%= render 'shared/content_title', title: "Sign Up" %>
<%= render 'form' %>
<% end %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "User Profile for: #{@user.username.capitalize}" %>

<div class='row'>
<div class='span9 well'>
	<ul>
		<li>Username: <%=@user.username%></li>
		<li>Member since: <%=nice_time(@user.created_at)%></li>
		<% if logged_in? && current_user == @user %>
			<%= link_to '[Edit User]', edit_user_path(@user) %>
			<% end %>
	</ul>
</div>
</div>
<br>
<p>Comments by: <%=@user.username%></p>

<%= render 'comments/comments' %>

<p>Posts by: <%=@user.username%></p>

<% @user.posts.each do |post| %>
  <%= render 'posts/posts', post: post %>
<% end %>